{% set name = "aws-request-signer" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_request_signer-{{ version }}.tar.gz
  sha256: 0d5a2b0ced30cfde0585db9ac7b56c419e41e529c17ec1d0a0ba16e26e827be5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
  run_constrained:
    - requests >=2.21.0,<3.0.0
    - requests_toolbelt >=0.8.0,<0.9.0

test:
  imports:
    - aws_request_signer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/iksteen/aws-request-signer
  summary: A python library to sign AWS requests using AWS Signature V4.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cedriccuypers
